% function [traces] = fdtd2_pml(domain,sources,receivers,opts)
%
% Wave equation in 2D with finite differences time domain with PML
%
% Outputs the traces at receivers generated by some point sources
%
% for reference see:
%
%   "Formulation and validation of Berenger's PML absorbing boundary for
%   the FDTF simulation of acoustic scattering" by Yuan, Borup, Wiskin, Berggren, Johnson
%   IEEE Transactions on Ultrasonics, Ferroelectrics and frequency control
%   vol 44, no 4, July 1997
%
% Inputs
%
%  domain (struct) domain specification
%   .c0   (real)   background velocity (m/s)
%   .f0   (real)   central frequency (Hz)
%   .xmin, .xmax, .ymin, .ymax 
%         (real)   extent of computational domain (excluding PML)A
%   .nx, .ny (int) number of points in x and y direction
%   .c    (array nx x ny) velocity at the grid nodes
%   .nt   (int)    number of time steps
%   .dt   (real)   time step
%   .npml [optional] (int)    number of PML layers (default: 8)
%   .rho  [optional] (real)   mass density (kg/m^3) (default: 1)
%
%  sources  (struct) source specification
%   .location (real array 2 x #sources) 
%             Each column gives the source's coordinates.
%   .signal   (cell array #sources x 1 or double array #sources x nt) 
%             the actual signal to inject can be given as functions of time or
%             as an array
%   .kind     [optional] (string)  'hard'  hard source 
%                                  'soft'  soft source (default)
%
%  receivers (real array 2 x #receivers). Each column corresponds to a receiver's
%            coordinates.
%
%  opts  (options, not necessary to give)
%   .plotwave (integer) if  =0 : no wave plotted (default)
%                       if  >0 : plot wave every .plotwave frames
%
%   .pausetime (real)   time (in seconds) to wait between two frames (default: 0.01 s)
%
%   .cmap    (#colors x 3) colormap (default: jet(255))
%
%   .verbose  (boolean) 0 : no output
%                       1 : basic diagnostic info (default)
%
% Outputs
%
%  traces  (#receivers x nt). Each row is the trace at corresponding receiver

%Author: Fernando Guevara Vasquez
% Yekaterina Epshteyn

function [traces] = fdtd2_pml(domain,sources,receivers,opts)

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Extract info about domain
c0=domain.c0;
f0=domain.f0;
xmin=domain.xmin; xmax=domain.xmax;
ymin=domain.ymin; ymax=domain.ymax;
nx=domain.nx; ny=domain.ny;
nt=domain.nt; dt=domain.dt;
if (~isfield(domain,'rho')) rho=1; else rho=domain.rho; end;
if (~isfield(domain,'npml')) npml=8; else npml=domain.npml; end;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Options
if (nargin<4) opts=[]; end;
if (~isfield(opts,'cmap')) cmap=jet(255); else cmap=opts.cmap; end;
if (~isfield(opts,'verbose')) verbose=1; else verbose=opts.verbose; end;
if (~isfield(opts,'plotwave')) plotwave=0; else plotwave=opts.plotwave; end;
if (~isfield(opts,'pausetime')) pausetime=0.01; else pausetime=opts.pausetime; end;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Compute some useful constants
la0 = c0/f0; % central wavelength
dx = (xmax-xmin)/(nx-1); dy = (ymax-ymin)/(ny-1);
ppwl = min(floor(la0/dx),floor(la0/dy)); % points per wavelength

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Grid (includes PML nodes)
gx = xmin+( (-npml-1):(nx+npml) )*dx ;% grid in x
gy = ymin+( (-npml-1):(ny+npml) )*dy ;% grid in y
[X,Y] = ndgrid(gx,gy);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Wave velocity lives on the same grid cells as the pressure
% extend it to include PML nodes as well
if (size(domain.c)~=[nx,ny]) error('c must be nx x ny'); end;
c = c0*ones(nx+2*npml+2,ny+2*npml+2);
c(1+npml + (1:nx), 1+npml + (1:ny)) = domain.c;
cmax = max(max(c));

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Partially Matched Layer (PML)
amax = 10;              % PML attenuation factor
pf = @(x) amax*(1-x).^2;% PML function (defined on [0,1] 0==BC, 1==medium)

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% get source specs
%   find indices for sources
nsrc=size(sources.location,2);
srcidx = zeros(nsrc,1);
ceilchk = @(x) (ceil(x)-x)>0.1;
for i=1:nsrc,
 srci = ceil((sources.location(1,i)-xmin)/dx) + npml + 2; 
 srcj = ceil((sources.location(2,i)-ymin)/dy) + npml + 2;
 srcidx(i) = sub2ind([nx + 2*(npml+1), ny + 2*(npml+1) ],srci,srcj);
 if (ceilchk((sources.location(1,i)-xmin)/dx) ...
    |ceilchk((sources.location(2,i)-ymin)/dy))
  fprintf('Warning: src %d: difference actual and intended position > tol\n',i);
 end;
end;
%   check to see which kind of sources we have
if (~isfield(sources,'kind')) srckind='soft'; else srckind=sources.kind; end;
%   check to see how the sources are given and make sure everything has the
%   right size
if (isa(sources.signal,'cell'))
 % sources are given as cell array of functions
 if (size(sources.signal) ~= [nsrc,1]) 
  error('cell array of sources needs to be nsrc x 1'); 
 end;
else
 % sources are given as samples
 if (size(sources.signal) ~= [nsrc,nt])
  error('array of samples for sources needs to be nsrc x nt');
 end;
end;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% find indices for receivers
nrcv=size(receivers,2);
rcvidx = zeros(nrcv,1);
for i=1:nrcv,
 rcvi = ceil((receivers(1,i)-xmin)/dx) + npml + 2; 
 rcvj = ceil((receivers(2,i)-ymin)/dy) + npml + 2; 
 rcvidx(i) = sub2ind([nx + 2*(npml+1), ny + 2*(npml+1) ],rcvi,rcvj);
 if (ceilchk((receivers(1,i)-xmin)/dx) | ceilchk((receivers(2,i)-ymin)/dy))
  fprintf('Warning: rcv %d: difference actual and intended position > tol\n',i);
 end;
end;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Print some diagnostic info
if (verbose)
fprintf([ ...
          '  mass density          = %e kg/m^3\n'...
          '  points per wavelength = %d\n'...
          '  central freq          = %e Hz\n'...
	  '  central wavelength    = %e m\n'...
	  '  period @ central freq = %e s\n'],...
	  rho,ppwl,f0,la0,1/f0);
fprintf('  time dt               = %e s\n',dt);
fprintf('  cfl=%d\n',cmax*dt/min(dx,dy));
fprintf('  max attenuation factor over a layer is: %g\n',exp(-amax*c0^2*rho*dt))
fprintf('  source kind = %s, signal is a %s\n',srckind,class(sources.signal))
end;


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Stencil initializations
% (note: this is not very elegant: we are storing the stencils as matrices)

% ** initialize time stencils for ux velocity update
stux1 = zeros(nx+2*npml+1,ny+2*(npml+1));
stux2 = zeros(nx+2*npml+1,ny+2*(npml+1));
%   usual time stencil for nodes where alpha_x = 0
stux1(npml+1+(1:nx),:) = 1;
stux2(npml+1+(1:nx),:) = -(dt/rho/dx);
%   exponential differencing for nodes where alpha_x > 0
%   left PML
alx = pf((0.5+(0:npml))'/(npml+1)); 
C=(alx*ones(1,ny+2*(npml+1))); C = C * c0^2 * rho; 
stux1(1:npml+1,:) = exp(-C*dt);
stux2(1:npml+1,:) = -(1/dx/rho)*(exp(-C*dt) - 1)./(-C);
%   right PML
alx = flipud(alx); 
C=(alx*ones(1,ny+2*(npml+1))); C = C * c0^2 * rho; 
stux1(npml+nx+(1:npml+1),:) = exp(-C*dt);
stux2(npml+nx+(1:npml+1),:) = -(1/dx/rho)*(exp(-C*dt) - 1)./(-C);

% ** initialize time stencils for uy velocity update
stuy1 = zeros(nx+2*(npml+1),ny+2*npml+1);
stuy2 = zeros(nx+2*(npml+1),ny+2*npml+1);
%    usual time stencil for nodes where alpha_y = 0
stuy1(:,npml+1+(1:ny)) = 1;
stuy2(:,npml+1+(1:ny)) = -(dt/rho/dy);
%    exponential differencing for nodes where alpha_y > 0
%    bottom PML 
aly = pf((0.5+(0:npml))/(npml+1)); 
C=(ones(nx+2*(npml+1),1)*aly); C = C* c0^2 * rho;
stuy1(:,1:npml+1) = exp(-C*dt);
stuy2(:,1:npml+1) = -(1/dy/rho)*(exp(-C*dt) - 1)./(-C);
%    top PML 
aly = fliplr(aly); 
C=(ones(nx+2*(npml+1),1)*aly); C = C* c0^2 * rho;
stuy1(:,npml+ny+(1:npml+1)) = exp(-C*dt);
stuy2(:,npml+ny+(1:npml+1)) = -(1/dy/rho)*(exp(-C*dt) - 1)./(-C);

% ** initialize time stencils for px pressure component
stpx1 = zeros(nx+2*npml,ny+2*(npml+1));
stpx2 = zeros(nx+2*npml,ny+2*(npml+1));
%    usual time stencil for nodes where alpha_x = 0
stpx1(npml+(1:nx),:) = 1;
stpx2(npml+(1:nx),:) = -(rho*dt/dx)*(c(npml+1+(1:nx),:).^2);
%    exponential differencing for nodes where alpha_x > 0
%    left PML
alx = pf((1:npml)'/(npml+1)); 
C = alx*ones(1,ny+2*(npml+1)); C = C * c0^2 * rho;
stpx1(1:npml,:) = exp(-C*dt);
stpx2(1:npml,:) = -(rho*c0^2/dx)*(exp(-C*dt) - 1)./(-C);
%    right PML
alx = flipud(alx); 
C = alx*ones(1,ny+2*(npml+1)); C = C * c0^2 * rho;
stpx1(npml+nx+(1:npml),:) = exp(-C*dt);
stpx2(npml+nx+(1:npml),:) = -(rho*c0^2/dx)*(exp(-C*dt) - 1)./(-C);

% ** initialize time stencils for py pressure component
stpy1 = zeros(nx+2*(npml+1),ny+2*npml);
stpy2 = zeros(nx+2*(npml+1),ny+2*npml);
%    usual time stencil for nodes where alpha_y = 0
stpy1(:,npml+(1:ny)) = 1;
stpy2(:,npml+(1:ny)) = -(rho*dt/dy)*(c(:,npml+1+(1:ny)).^2);
%    exponential differencing for nodes where alpha_y > 0
%    left PML
aly = pf((1:npml)/(npml+1)); 
C = ones(nx+2*(npml+1),1)*aly; C = C * c0^2 * rho;
stpy1(:,1:npml) = exp(-C*dt);
stpy2(:,1:npml) = -(rho*c0^2/dy)*(exp(-C*dt) - 1)./(-C);
%    right PML
aly = fliplr(aly); 
C = ones(nx+2*(npml+1),1)*aly; C = C * c0^2 * rho;
stpy1(:,npml+ny+(1:npml)) = exp(-C*dt);
stpy2(:,npml+ny+(1:npml)) = -(rho*c0^2/dy)*(exp(-C*dt) - 1)./(-C);

% index of not PML nodes
C = zeros(nx+2*(npml+1),ny+2*(npml+1));
C(npml+1+(1:nx),npml+1+(1:ny))=1;
notpml=find(C);


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% initialization (everything quiet)
px = zeros(nx+2*(npml+1),ny+2*(npml+1)); % pressure x split
py = zeros(nx+2*(npml+1),ny+2*(npml+1)); % pressure y split
p  = zeros(nx+2*(npml+1),ny+2*(npml+1)); % pressure (unsplit)
ux = zeros(size(px)-[1,0]);   % x velocity
uy = zeros(size(px)-[0,1]);   % y velocity
src = zeros(nsrc,1);   % for sources

tic; % start timing

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Actual Finite Differences Time Domain updated
for i=1:nt,
 % spatial derivatives of p
 Dxp = diff(p,1,1); Dyp = diff(p,1,2);

 % update velocity
 ux = ux.*stux1 + Dxp.*stux2;
 uy = uy.*stuy1 + Dyp.*stuy2;
 
 % spatial derivatives of u
 Dxux = diff(ux,1,1); Dyuy = diff(uy,1,2);
 % update pressure
 px(2:end-1,:) = px(2:end-1,:).*stpx1 + Dxux.*stpx2;
 py(:,2:end-1) = py(:,2:end-1).*stpy1 + Dyuy.*stpy2;

 % zero BC
 px(1,:)=0; px(end,:)=0; px(:,1)=0; px(:,end)=0;
 py(1,:)=0; py(end,:)=0; py(:,1)=0; py(:,end)=0;

 % update p
 p = px + py;

 % compute source
 if (isa(sources.signal,'cell'))
  % sources are specified as function
  for j=1:nsrc,
   fun = sources.signal{j};
   src(j) = fun(i*dt);
  end;
 else
  % sources are given as an array
   src = sources.signal(:,i);
 end;

 % apply source
 switch lower(srckind)
  case 'soft'
   p(srcidx) = p(srcidx) + src;
  case 'hard'
   p(srcidx) = src;
  otherwise
   error(sprintf('Unknown source kind : %s',srckind));
 end;

 % make sure we maintain px=py in the internal nodes (this is wasteful!)
 px(notpml)=p(notpml)/2; py(notpml)=p(notpml)/2;

 % get traces at receivers
 traces(:,i) = p(rcvidx);

  if (mod(i,plotwave)==0)
         figure(1);
   clf;
  hold on;
    imagesc(gx/la0,gy/la0,p.'); caxis(max(max(abs(p)))*[-1,1]); axis xy;
  colormap(cmap);
    for j=1:size(sources.location,2)
    plot(sources.location(1,j)/la0,sources.location(2,j)/la0,'kx');
  end;
  for j=1:nrcv,
   plot(receivers(1,j)/la0,receivers(2,j)/la0,'ko');
  end;
  hold off;
  title(sprintf('t=%e s\n',i*dt)); axis equal; axis tight;
  xlabel('x (\lambda_0)'); ylabel('y (\lambda_0)');
  pause(pausetime)
 end;
  end;
te=toc; % stop timing
if (verbose)
 fprintf('** time per iter= %f s\n',te/nt);
end
